services:
    minio:
        image: minio/minio:latest
        container_name: minio_demo
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minioadmin123
            MINIO_ROOT_PASSWORD: minioadmin123
        volumes:
            - minio_data:/data
        command: server /data --console-address ":9001"
        restart: unless-stopped

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        restart: always
        ports:
            - "15672:15672"
            - "5672:5672"

volumes:
    minio_data: {}